[package]
name = "simuforge-material"
version = "0.1.0"
edition = "2021"

[dependencies]
simuforge-core = { path = "../core" }
glam = { workspace = true }
bytemuck = { workspace = true }
fast-surface-nets = { workspace = true }
rayon = { workspace = true }
